### ISSUE TITLE
Put UCSUSA data into mongo

### ISSUE THREAD

**Issue by michaelKurowski** [jpitucha/houston#12]
Put https://www.ucsusa.org/resources/satellite-database data into MongoDB.
You need #6 to be done first before starting with this task.

**Comment by michaelKurowski** [comment]
The ticket after that is
https://github.com/jpitucha/houston/issues/9

**Comment by jpitucha** [comment]
I would use this https://www.npmjs.com/package/mongoose-fuzzy-searching
