### ISSUE TITLE
Setup nodemon

### ISSUE THREAD

**Issue by michaelKurowski** [jpitucha/houston#5]
After your'e done with #3, setup a nodemon that will be watching your code and reloading the application when you'll be editing the code. It's needed to work comfortably with Docker later on

**Comment by jpitucha** [comment]
is there any config needed? i have it installed globally and type just nodemon build/index.js and voila.
the only thing that comes to my mind is saving it at dev dependency. what do You think?

**Comment by michaelKurowski** [comment]
Include it in dev deps and add it to the `start` script or `dev` script to run via `npx`.
